services:
  # Main container for the project.
  manga-info:
    build: .
    stdin_open: true          # Keep STDIN open
    tty: true                 # Allocate a pseudo TTY
    container_name: manga_info
    working_dir: /app
    volumes:
      - main_proj:/app
    command: python app.py
  
  # test:
  #   build: .
  #   volumes:
  #     - .:/app
  #   command: pytest -s --maxfail=1 --disable-warnings      # Runs pytest as the command
  #   depends_on:
  #     - manga-info

  # Testing dockerfile in src/unit-test
  test:
    build: ./unit-test
    working_dir : /app
    command: pytest
    volumes:
      - main_proj:/app

volumes:
  main_proj:
