version: '3'
services:
  # Main container for the project.
  manga-info:
    build: .
    stdin_open: true          # Keep STDIN open
    tty: true                 # Allocate a pseudo TTY
    container_name: manga_info
    working_dir: /app
    volumes:
      - .:/app
    command: python app.py
  
  # test:
  #   build: .
  #   volumes:
  #     - .:/app
  #   command: pytest -s --maxfail=1 --disable-warnings      # Runs pytest as the command
  #   depends_on:
  #     - manga-info

  # Testing dockerfile in src/unit-test
  test:
    build: src/unit-test
    working_dir : /dev
    command: pytest -s --maxfail=1 --disable-warnings
    depends_on:
      - manga-info
    volumes:
      - .:/app
